
package simple.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "http://xmlsoap.org/Ping", wsdlLocation = "file:/D:/users/_SOFTWARE_/metro-standalone-2.2.1/samples/wssc/src/etc/server/PingService.wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PINGSERVICE_EXCEPTION;
    private final static QName PINGSERVICE_QNAME = new QName("http://xmlsoap.org/Ping", "PingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/users/_SOFTWARE_/metro-standalone-2.2.1/samples/wssc/src/etc/server/PingService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PINGSERVICE_WSDL_LOCATION = url;
        PINGSERVICE_EXCEPTION = e;
    }

    public PingService() {
        super(__getWsdlLocation(), PINGSERVICE_QNAME);
    }

    public PingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation) {
        super(wsdlLocation, PINGSERVICE_QNAME);
    }

    public PingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PINGSERVICE_QNAME, features);
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "PingPort")
    public IPingService getPingPort() {
        return super.getPort(new QName("http://xmlsoap.org/Ping", "PingPort"), IPingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "PingPort")
    public IPingService getPingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlsoap.org/Ping", "PingPort"), IPingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PINGSERVICE_EXCEPTION!= null) {
            throw PINGSERVICE_EXCEPTION;
        }
        return PINGSERVICE_WSDL_LOCATION;
    }

}
