package org.xmlsoap.ping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-13T02:44:36.375+01:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "PingService", 
                  wsdlLocation = "https://localhost:8443/jaxws-sc/simple?wsdl",
                  targetNamespace = "http://xmlsoap.org/Ping") 
public class PingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlsoap.org/Ping", "PingService");
    public final static QName PingPort = new QName("http://xmlsoap.org/Ping", "PingPort");
    static {
        URL url = null;
        try {
            url = new URL("https://localhost:8443/jaxws-sc/simple?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://localhost:8443/jaxws-sc/simple?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "PingPort")
    public IPingService getPingPort() {
        return super.getPort(PingPort, IPingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "PingPort")
    public IPingService getPingPort(WebServiceFeature... features) {
        return super.getPort(PingPort, IPingService.class, features);
    }

}
